#!/bin/sh
# actually a full build, maybe rename this file

set -e

IAM=$(which $0)
SCRIPTDIR=${IAM%/*}

MAKE="$SCRIPTDIR/make"

# Workaround for Makefile bug; clang will barf if ar is called on existing files
rm -f libchicken-boot*.a

$MAKE spotless
$MAKE boot-chicken
$MAKE CHICKEN=./chicken-boot spotless
$MAKE CHICKEN=./chicken-boot
