#!/bin/sh
# actually a full build, maybe rename this file

set -e

IAM=$(which $0)
SCRIPTDIR=${IAM%/*}

MK="$SCRIPTDIR/make"

# Workaround for Makefile bug; clang will barf if ar is called on existing files
rm -f libchicken-boot*.a

$MK spotless
$MK boot-chicken
$MK CHICKEN=./chicken-boot spotless
$MK CHICKEN=./chicken-boot
