#!/bin/sh
set -e

IAM=$(which $0)
SCRIPTDIR=${IAM%/*}
SCRIPTDIR=$(cd $SCRIPTDIR && pwd)
MAKE="$SCRIPTDIR/make"

#VER="$1"
# make dist expects a hardcoded buildversion
VER=$(cat buildversion)

rm -f chicken-$VER.tar.gz
$MAKE CHICKEN=./chicken-boot dist
md5sum chicken-$VER.tar.gz > chicken-$VER.tar.gz.md5
