#!/bin/bash

#/ usage: $0 [TAG]
#/  Push checked-out stability branch and optional tag $TAG.

# Since TAG is optional, we can't derive stability/* name from TAG.
# (We don't check TAG format either...)

# If you use --tags it will push all tags including core tags, maybe this is ok?
# Alternatively break this up into two steps: git push github; git push github tag $TAG
# Alternatively, push all tags found in the stability branch (you'd have to use BASEVER
# as the starting point).

BRANCH=$(git rev-parse --abbrev-ref HEAD)
[[ ${BRANCH%/*} == "stability" ]] || { echo "Check out stability branch first"; exit 1; }
BASEVER=${BRANCH#*/}

TAG=$1

git push call-cc $BRANCH || exit 1

if [[ -n "$TAG" ]]; then
  git push call-cc tag $TAG
fi
