#!/bin/bash
set -e
trap "echo '*** release failed ***' >&2" ERR

#VER=$1
#if [ -z "$VER" ]; then echo "usage: $0 4.7.0.5-st" >&2; exit 1; fi

IAM=$(which $0)
SCRIPTDIR=${IAM%/*}

VER=$(cat buildversion)
echo "Building version $VER for release..."; sleep 1

# FIXME!!!
#MAKE='make PLATFORM=macosx C_COMPILER=gcc-4.2'
MAKE='make PLATFORM=macosx C_COMPILER=clang'

$SCRIPTDIR/build $VER
$SCRIPTDIR/make-dist $VER
$SCRIPTDIR/test-dist $VER

### Do the copy step manually for now (using ./upload).
