#!/bin/bash
set -e
trap "echo '*** release failed ***' >&2" ERR

IAM=$(which $0)
SCRIPTDIR=${IAM%/*}
source $SCRIPTDIR/common

get_building_ver_and_id
echo "Building version $VER_ID for release..."; sleep 1

$SCRIPTDIR/build
$SCRIPTDIR/make-dist
$SCRIPTDIR/test-dist

### Do the copy step manually for now (using ./upload).
