#!/bin/sh
set -e

IAM=$(which $0)
SCRIPTDIR=${IAM%/*}
source $SCRIPTDIR/common

SCRIPTDIR=$(cd $SCRIPTDIR && pwd)
MK="$SCRIPTDIR/make"

get_built_ver_and_id

rm -rf chicken-$VER            # `make dist` doesn't know about our _ID component
tar zxf chicken-$VER_ID.tar.gz

cd chicken-$VER                # again, no _ID component
$MK PREFIX=$PWD/inst         # Unfortunately `make check` requires chicken to be installed
$MK PREFIX=$PWD/inst install
$MK PREFIX=$PWD/inst check   # Setting prefix here is not necessary, but not harmful
cd $OLDPWD

# rm -rf chicken-$VER        # More often than not, I want to keep the build
# can also make -f Makefile.macosx buildhead prior to this

